IF EXIST "%1..\Music Players\MusicBee\" COPY /B /Y "%2" "%1..\Music Players\MusicBee\"
rem IF EXIST "%1..\Music Players\Winamp\" COPY /B /Y "%2" "%1..\Music Players\Winamp\"
rem IF EXIST "%1..\Music Players\MediaMonkey\" COPY /B /Y "%2" "%1..\Music Players\MediaMonkey\"
rem IF EXIST "%1..\Music Players\foobar2000\" COPY /B /Y "%2" "%1..\Music Players\foobar2000\"
rem IF EXIST "%1..\Music Players\xmplay\Plugins\" COPY /B /Y "%2" "%1..\Music Players\xmplay\Plugins\"